# Generated by Django 6.0.6 on 2026-07-06 17:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_name_at_order',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Order Received'), ('PREPARING', 'In Kitchen - Preparing'), ('READY', 'Ready for Pickup / Delivery'), ('COMPLETED', 'Completed')], db_index=True, default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menuitem'),
        ),
    ]
