# Generated by Django 6.0.6 on 2026-07-06 17:48

import uuid
from decimal import Decimal
from django.db import migrations


def populate_existing_data(apps, schema_editor):
    Order = apps.get_model("restaurant", "Order")
    OrderItem = apps.get_model("restaurant", "OrderItem")

    # 1. Populate Order UUIDs and Financial Snapshots
    for order in Order.objects.all():
        if not order.tracking_token:
            order.tracking_token = uuid.uuid4()
        
        # Calculate subtotal from related items
        items = OrderItem.objects.filter(order=order)
        subtotal = sum(item.price_at_order * item.quantity for item in items)
        
        order.subtotal_amount = Decimal(str(subtotal)).quantize(Decimal("0.01"))
        order.tax_rate = Decimal("0.0500")
        order.tax_amount = (order.subtotal_amount * Decimal("0.05")).quantize(Decimal("0.01"))
        
        # Ensure total_amount matches exactly
        order.total_amount = order.subtotal_amount + order.tax_amount
        order.save()

    # 2. Populate OrderItem item_name_at_order snapshot
    for item in OrderItem.objects.all():
        if not item.item_name_at_order:
            if item.menu_item:
                item.item_name_at_order = item.menu_item.name
            else:
                item.item_name_at_order = "Unknown Item"
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order_subtotal_amount_order_tax_amount_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_existing_data, reverse_code=migrations.RunPython.noop),
    ]
