# Generated by Django 6.0.6 on 2026-07-06 17:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20260706_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
