# Generated by Django 6.0.6 on 2026-07-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_order_tracking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category_name_at_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Order Received'), ('PREPARING', 'In Kitchen - Preparing'), ('READY', 'Ready for Pickup / Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=20),
        ),
    ]
