# Generated by Django 6.0.6 on 2026-07-06 18:29

from django.db import migrations


def populate_managers_group_and_categories(apps, schema_editor):
    # 1. Ensure the 'Managers' group exists
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Managers")

    # 2. Populate category_name_at_order for existing OrderItems
    OrderItem = apps.get_model("restaurant", "OrderItem")
    for item in OrderItem.objects.all():
        if not item.category_name_at_order:
            if item.menu_item and item.menu_item.category:
                item.category_name_at_order = item.menu_item.category.name
            else:
                item.category_name_at_order = "Unknown Category"
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_orderitem_category_name_at_order_alter_order_status'),
    ]

    operations = [
        migrations.RunPython(populate_managers_group_and_categories, reverse_code=migrations.RunPython.noop),
    ]
