# Generated by Django 6.0.6 on 2026-07-07 04:26

import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_create_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/', validators=[restaurant.models.validate_image_file]),
        ),
    ]
