# Generated by Django 6.0.6 on 2026-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='special_instructions',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
