# Generated by Django 6.0.6 on 2026-07-08 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_orderitem_special_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_preparation_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PRIORITY', 'Priority'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=10),
        ),
    ]
